version: '3.9'
services:
  app:
    build: ./backend
    container_name: travel_api
    depends_on: [db]
    environment:
      APP_ENV: local
      APP_KEY: base64:placeholderkey=
      APP_DEBUG: 'true'
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: travel
      DB_USERNAME: root
      DB_PASSWORD: root
      MAIL_MAILER: log
      JWT_TTL: 60
    working_dir: /laravel
    volumes:
      - ./backend/laravel:/laravel
      - ./backend/custom:/tmp/custom
    ports:
      - "9000:9000"

  web:
    image: nginx:alpine
    container_name: travel_nginx
    depends_on: [app]
    volumes:
      - ./backend/laravel:/laravel
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  db:
    image: mysql:8
    container_name: travel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
    container_name: travel_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  db_data:
